### ISSUE TITLE
Gnome 3.22 support?

### ISSUE THREAD

**Issue by inducer** [schuhumi/gnome-shell-extension-onboard-integration#4]
I tried loading the extension into gnome-shell 3.22, but it wasn't obvious that it was doing anything useful...

**Comment by schuhumi** [comment]
You need to have onboard installed and the virtual keyboard setting in Gnome activated. If the onboard keyboard shows up when you start onboard manually and Gnome's integrated keyboard (caribou) shows up when tapping a textbox, something has gone wrong as it's this extensions job to link the two. Have you got this extension working on Gnome 3.20?

Also I recommend to not use this extension and rather stick to caribou, I have created a few things to make caribou more useful:
- this extension resizes the workspace when caribou is opened so that it doesn't cover your input field: https://github.com/schuhumi/gnome-shell-extension-caribou-resize-workspace
- this extension enables you to call caribou with a swipe from the bottom screen edge (for programs like chromium which don't call the virtual keyboard automatically): https://github.com/schuhumi/gnome-shell-extension-slide-for-keyboard
- I made a new layout called "tablet" which is included in Gnome 3.20 onwards. You can activate it like that: gsettings set org.gnome.shell.keyboard keyboard-type tablet

Those 3 things should give you a environment like this: https://imgur.com/a/PA66G . I know that caribou doesn't do word prediction and stuff, but this onboard extension here is just a ugly hack, not reliable and just overall not elegant. Gnome wants to replace caribou with something new and shiny, so this virtual keyboard dilemma will end eventually

**Comment by inducer** [comment]
Thanks for making these things, and for taking the time to type out a reply to my question.

Your recommended feels like the way to go, and it _almost_ works, but:

https://github.com/schuhumi/gnome-shell-extension-slide-for-keyboard/issues/1

I'll close this since I won't pursue `onboard` further.

**Comment by phil-harmoniq** [comment]
I'm sorry if this isn't the appropriate place to ask this but I can't find any discussion of your tablet layout for Caribou. It seems there is an error in the US version of the layout. The 'y' and 'z' keys are still set the way they would be for a german keyboard. any ideas?

**Comment by schuhumi** [comment]
Damn, you're right.. actually I named one layout qwertz and the other qwerty, but forgot to update z and y. The official way of fixing it is this: you have a look at the code, it's located here: https://github.com/GNOME/caribou/tree/master/data/layouts/tablet

Then you fix the issue and create a patch. On Gnome's Bugzilla create a bug regarding this issue and attach your patch. Someone privileged will take your patch and submit it, and it will eventially roll out to all Gnome installations. Gnome's Bugzilla, specifically the layout contribution: https://bugzilla.gnome.org/show_bug.cgi?id=760470

Also while you're waiting for the patch to roll out you can do a simple temporary local fix: The caribou layouts are stored in cleartext somewhere in /usr/share/ if I'm not mistaken. There you can swap x and y and it will stay this way until an update changes the file.

I don't have my linux machine at hand, but in case you're feeling like contributing to Gnome this would make a nice and simple patch :)
