### ISSUE TITLE
installation from extensions.gnome.org give error

### ISSUE THREAD

**Issue by thekswenson** [schuhumi/gnome-shell-extension-onboard-integration#6]
I'm running Ubuntu 17.04 with Gnome Shell 3.24.0.

Installation from https://extensions.gnome.org/extension/992/onboard-integration/ results in an error.

**Comment by rickysarraf** [comment]
We already worked with onboard upstream to get this extension merged. If
you have the latest onboard, it should have the extension too

s3nt fr0m a $martph0ne, excuse typ0s

**Comment by thekswenson** [comment]
Thanks for the comment.

I'm not quite sure what you mean by this.  I assume you mean either:

1. installing onboard will disable caribou automatically, or
2. will install the extension.

Neither appear to be true since caribou pops up instead of onboard.  Also, the extension does not show up in Tweak Tool.

**Comment by rickysarraf** [comment]
You don't need to install the extension from here. Your distribution needs
to package the extension.

s3nt fr0m a $martph0ne, excuse typ0s

On 12-May-2017 20:18, "thekswenson" <notifications@github.com> wrote:

I'm not quite sure what you mean by this. I assume you mean either:

   1. installing onboard will disable caribou automatically, or
   2. will install the extension.

Neither appear to be true since caribou pops up instead of onboard. Also,
the extension does not show up in Tweak Tool.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/schuhumi/gnome-shell-extension-onboard-integration/issues/6#issuecomment-301097576>,
or mute the thread

**Comment by thekswenson** [comment]
OK...
   it works after installing the ubuntu package.
This setup is rather confusing...
   it's a shame.

Thanks for the nice work!
